* TODO Introduction
  Deep Learning and machine learning in general are hot topic of discussion over last several years. From historical perspective this is very interesting because research in artificial intelligence started in mid 20th century with bold promises that didn't come into fruition when the century ended. It wasn't the case that the research failed to bring any fascinating innovations but it merely failed to bring machines that could see or to understand a human voice. There were many reasons for this but perhaps the most import is that both vision and voice recognition are much more complex that would our own intuition suggest since it comes very naturally to us.

  The long awaited breakthrough came about ten years later in application of neural networks. It come somewhat unexpected at times when large portion of research community stopped paying attention to them. Neural networks are one of the oldest models that many saw as failed endeavor. From year 2010 sources of technical news are constantly coming with new and exciting stories of deep learning application in almost all walks of life. Leading fortune 500 companies such as Amazon, Apple, Facebook or Google are investing enormous resources into machine learning research.

  Technology that we use today is taking full advantage of this recent development. Mobile devices that are in our pockets are capable of identifying specific human face. They are capable to understand and react to voice commands. Self-driving cars are most likely about to become part of our every day life.

  In the midst of all of this is one specific model that is quite possible the largest contributor to current state of affairs. This model is called [[gls:cnn][CNN]]. Aim of this thesis is to document its background and basic theoretical concepts. Several examples of applications of [[gls:cnn][CNN]] will be discussed.
  Structure of [[gls:cnn][CNN]] model will be proposed in one the available software tools. Resulting model will be tested on [[gls:ilsvrc][ILSVRC]] dataset and its achieved results will be compared with submissions from previous years' participants.
